services:
  mariadb:
    image: docker.arvancloud.ir/yobasystems/alpine-mariadb
    container_name: mariadb
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
      MYSQL_USER: ${MYSQL_USER:-admin}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-admin}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-nikamooz}
    volumes:
      - mariadb_data:/var/lib/mysql
    mem_limit: ${MEM_LIMIT:-1g}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  mariadb_data:
