services:
  redpanda:
    container_name: redpanda
    image: docker.arvancloud.ir/redpandadata/redpanda:latest
    command:
      - redpanda
      - start
      - --smp 1
      - --memory 1G
      - --kafka-addr internal://0.0.0.0:29092,external://0.0.0.0:9092
      - --advertise-kafka-addr internal://redpanda:29092,external://localhost:9092
    ports:
      - "9092:9092"
      - "29092:29092"
    mem_limit: ${MEM_LIMIT:-2g}
    healthcheck:
      test: ["CMD", "rpk", "cluster", "info", "||", "exit 1"]
      start_period: 10s
      interval: 5s
      timeout: 10s
      retries: 5
    restart: unless-stopped
    networks:
      - services

  console:
    container_name: redpanda-console
    image: docker.arvancloud.ir/redpandadata/console:latest
    entrypoint: /bin/sh
    command: -c 'echo "$$CONSOLE_CONFIG_FILE" > /tmp/config.yml; /app/console'
    environment:
      CONFIG_FILEPATH: /tmp/config.yml
      CONSOLE_CONFIG_FILE: |
        kafka:
          brokers: ["redpanda:29092"]
        redpanda:
          adminApi:
            enabled: true
            urls: ["http://redpanda:9644"]
    ports:
      - 9300:8080
    depends_on:
      redpanda:
        condition: service_healthy
    mem_limit: ${MEM_LIMIT:-256m}
    restart: unless-stopped
    networks:
      - services

  kafkaHQ:
    image: docker.arvancloud.ir/tchiotludo/akhq
    container_name: kafkaHQ
    hostname: kafkaHQ
    ports:
      - 9100:8080
    environment:
      AKHQ_CONFIGURATION: |
        akhq:
          connections:
            docker-kafka-server:
              properties:
                bootstrap.servers: "redpanda:29092"
    depends_on:
      redpanda:
        condition: service_healthy
    mem_limit: ${MEM_LIMIT:-512m}
    restart: unless-stopped
    networks:
      - services

  kafka-ui:
    container_name: kafka-ui
    image: docker.arvancloud.ir/kafbat/kafka-ui:latest
    ports:
      - 9200:8080
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: redpanda:29092
      DYNAMIC_CONFIG_ENABLED: 'true'
    depends_on:
      redpanda:
        condition: service_healthy
    mem_limit: ${MEM_LIMIT:-256m}
    restart: unless-stopped
    networks:
      - services

networks:
  services:
    name: ${APP_NAME:-sepahram}_network
