FROM docker.arvancloud.ir/apache/spark:4.0.1-scala2.13-java21-python3-ubuntu

USER root
ENV SPARK_HOME=/opt/spark

# Install system deps
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    curl wget python3-pip python3-setuptools python3-dev build-essential ssh \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

COPY requirements.txt /tmp/
RUN pip3 install --no-cache-dir -r /tmp/requirements.txt

COPY conf/spark-defaults.conf $SPARK_HOME/conf/
RUN echo "spark.jars.ivy /opt/spark" >> $SPARK_HOME/conf/spark-defaults.conf

WORKDIR $SPARK_HOME
EXPOSE 4040 4041 4042 8080 8081 8082 8888
