services:
  minio:
    image: docker.arvancloud.ir/minio/minio:latest
    container_name: minio
    hostname: minio
    command:
      - server
      - /data             
      - "--address"
      - "0.0.0.0:9000"
      - "--console-address"
      - "0.0.0.0:9001"
    expose:
      - "9000"
      - "9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data
    environment:
      MINIO_ROOT_PASSWORD: sepahram
      MINIO_ROOT_USER: sepahram
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9000/minio/health/live || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G
    profiles:
      - minio
    networks:
      - sepahram_net

volumes:
  minio-data:

networks:
  sepahram_net:
    name: ${APP_NAME:-sepahram}_network
