version: '3.8'

volumes:
  minio1-data:
  minio2-data:
  minio3-data:

services:
  minio1:
    image: docker.arvancloud.ir/minio/minio:latest
    container_name: minio1
    hostname: minio1
    volumes:
      - minio1-data:/data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
      MINIO_VOLUMES: "http://minio{1...3}:9000/data"
    command: server --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    ports:
      - "9001:9001"
      - "9000:9000"
    restart: unless-stopped
    networks:
      - sepahram_net

  minio2:
    image: docker.arvancloud.ir/minio/minio:latest
    container_name: minio2
    hostname: minio2
    volumes:
      - minio2-data:/data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
      MINIO_VOLUMES: "http://minio{1...3}:9000/data"
    command: server --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    ports:
      - "9002:9001"
    restart: unless-stopped
    networks:
      - sepahram_net

  minio3:
    image: docker.arvancloud.ir/minio/minio:latest
    container_name: minio3
    hostname: minio3
    volumes:
      - minio3-data:/data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
      MINIO_VOLUMES: "http://minio{1...3}:9000/data"
    command: server --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    ports:
      - "9003:9001"
    restart: unless-stopped
    networks:
      - sepahram_net

networks:
  sepahram_net:
    name: ${APP_NAME:-sepahram}_network
