services:
  minio:
    image: docker.arvancloud.ir/bitnami/minio:2025.4.22
    container_name: minio
    environment:
      - MINIO_ROOT_USER=minio-root-user
      - MINIO_ROOT_PASSWORD=minio-root-password
      - MINIO_API_PORT_NUMBER=9000
      - MINIO_CONSOLE_PORT_NUMBER=9001
      - MINIO_SCHEME=http
      - MINIO_DEFAULT_BUCKETS=irisa-warehouse
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/bitnami/minio/data
    mem_limit: ${MEM_LIMIT:-2g}
    healthcheck:
      test: [ "CMD", "mc", "ls", "local", "|", "grep", "irisa-warehouse" ]
      interval: 2s
      timeout: 10s
      retries: 2
      start_period: 15s
    restart: unless-stopped
    profiles:
      - minio
    networks:
      - services

  spark-master:
    build:
      context: .
      dockerfile: Dockerfile.Spark4-Official.final
    image: sepahram/spark4:apache
    container_name: spark-master
    ports:
      - "9080:8080"
      - "7077:7077"
    command: >
      bash -c "bin/spark-class org.apache.spark.deploy.master.Master
               --host spark-master --port 7077 --webui-port 8080"
    volumes:
      - ./notebooks:/opt/spark/notebooks
      - ./data/data:/spark-data
      - ./data/apps:/spark-app
      - ./data/jars:/spark-jars
    mem_limit: ${MEM_LIMIT:-2g}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped
    networks:
      - services

  spark-worker:
    build:
      context: .
      dockerfile: Dockerfile.Spark4-Official.final
    image: sepahram/spark4:apache
    container_name: spark-worker
    depends_on:
      spark-master:
        condition: service_started
    ports:
      - "9081:8081"
    command: >
      bin/spark-class org.apache.spark.deploy.worker.Worker
      --webui-port 8081
      --cores 2
      --memory 2G
      spark://spark-master:7077
    volumes:
      - ./notebooks:/opt/spark/notebooks
      - ./data/data:/spark-data
      - ./data/apps:/spark-app
      - ./data/jars:/spark-jars
    mem_limit: ${MEM_LIMIT:-4g}
    restart: unless-stopped
    networks:
      - services

  jupyter:
    build:
      context: .
      dockerfile: Dockerfile.Spark4-Official.final
    image: sepahram/spark4:apache
    container_name: jupyter
    depends_on:
      spark-master:
        condition: service_started
    ports:
      - "9888:8888"
      - "4040:4040"
      - "4041:4041"
      - "4042:4042"
    command: bash -c "cd /opt/spark/notebooks && jupyter lab --ip=0.0.0.0 --port=8888 --no-browser --allow-root --ServerApp.token='' --ServerApp.password=''"
    environment:
      - PYSPARK_PYTHON=python3
      - PYSPARK_DRIVER_PYTHON=jupyter
      - PYSPARK_DRIVER_PYTHON_OPTS="notebook"
    volumes:
      - ./notebooks:/opt/spark/notebooks
      - ./data/data:/spark-data
      - ./data/apps:/spark-app
      - ./data/jars:/spark-jars
    mem_limit: ${MEM_LIMIT:-2g}
    restart: unless-stopped
    networks:
      - services

volumes:
  minio-data:

networks:
  services:
    name: ${APP_NAME:-sepahram}_network
